SELECT
       schoolkey,
       schoolname,
       schooltype,
       schooladdress,
       schoolcity,
       schoolcounty,
       schoolstate,
       localeducationagencyname,
       localeducationagencykey,
       stateeducationagencyname,
       stateeducationagencykey,
       educationservicecentername,
       educationservicecenterkey,
       lastmodifieddate
FROM
     analytics.SchoolDim
