DROP TABLE IF EXISTS fif.Survey;
DROP TABLE IF EXISTS fif.StaffSectionAssociation;
DROP TABLE IF EXISTS fif.Staff;
DROP TABLE IF EXISTS fif.StudentSection;
DROP TABLE IF EXISTS fif.Section;
DROP TABLE IF EXISTS fif.StudentContact;
DROP TABLE IF EXISTS fif.ContactPerson;
DROP TABLE IF EXISTS fif.StudentSchool;
DROP TABLE IF EXISTS fif.School;
