import { StudentClassType } from '../../Student/types/StudentClassType';

const firstSection: Array<StudentClassType> = [
  {
    studentschoolkey: '1',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '1',
    pictureurl: 'https://api.adorable.io/avatars/164/abott@adorable.png',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
  {
    studentschoolkey: '2',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '2',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
  {
    studentschoolkey: '3',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '3',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
  {
    studentschoolkey: '4',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '4',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
  {
    studentschoolkey: '5',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '5',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
];

const secondSection: Array<StudentClassType> = [
  {
    studentschoolkey: '6',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '6',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
  {
    studentschoolkey: '7',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '7',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
  {
    studentschoolkey: '8',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '8',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
  {
    studentschoolkey: '9',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '9',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
  {
    studentschoolkey: '10',
    studentfirstname: 'John',
    studentlastname: 'Doe',
    studentmiddlename: '10',
    pictureurl: '',
    email: 'student@test.com',
    guardianInformation: {
      name: 'Guardian Name',
      email: 'test@test.com',
      phone: '555-555-5555',
      address: 'Test Address',
      preferredContactMethod: 'Phone call',
      bestTimeToContact: 'Friday morning',
      relationship: 'Mother',
      contactNotes: 'Write a message before calling',
    },
  },
];

const studentsList: {
  '1': Array<StudentClassType>;
  '2': Array<StudentClassType>;
} = {
  '1': firstSection,
  '2': secondSection,
};

export default studentsList;
